version: "3.9"
services:
  dias:
    build:
      dockerfile: dias.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - README.md:/docs/README.md
    networks:
      - road
  asset-server:
    build:
      dockerfile: asset-server.dockerfile
    ports:
      - "8001:8001"
    networks:
      - road
  admin-server:
    build:
      dockerfile: admin-server.dockerfile
    ports:
      - "8002:8002"
    networks:
      - road